### ISSUE TITLE
Bug in OpenCL Conversions

### ISSUE THREAD

**Issue by rperrot** [rperrot/openMVG#9]
https://github.com/rperrot/openMVG/blob/12e3769bc08da644b172f9ac0cb92a302794d4c1/src/software/MVS/OpenCLWrapper.cpp#L553

Width -> Height

**Comment by pmoulon** [comment]
Do you must use CL_IMAGE_HEIGHT too?

**Comment by rperrot** [comment]
Yes here it's height instead of width

**Comment by rperrot** [comment]
Fixed by commit : https://github.com/rperrot/openMVG/commit/cc1804ddf4c3576705217982b0a2a659488b54ab
